version: '3.3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db
    networks:
      - app-network

  server:
    depends_on:
      - db
    build:
      context: ./packages/server
    container_name: server
    restart: always
    environment:
      - MONGO_URI=mongodb://db:27017/forwardFocusDb
      - PORT=4000
    ports:
      - '4000:4000'
    networks:
      - app-network

  client:
    depends_on:
      - server
    build:
      context: ./packages/client
    ports:
      - '3000:3000'
    container_name: client
    restart: always
    stdin_open: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
