version: '3.3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db
    networks:
      - app-network

  server:
    depends_on:
      - db
    build:
      context: ./packages/server
    container_name: server
    restart: always
    environment:
      - MONGO_URI=mongodb://db:27017/wikiDB
      - PORT=4000
    ports:
      - '4000:4000'
    volumes:
      - ./packages/server:/packages/server
      - ./packages/server/node_modules:/packages/server/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./packages/client
    ports:
      - '3000:3000'
    container_name: client
    restart: always
    environment:
      - REACT_URI=client
    stdin_open: true
    volumes:
      - ./packages/client:/packages/client
      - ./packages/client/node_modules:/packages/client/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
